COPY enem (

NU_INSCRICAO, NU_ANO, NU_IDADE, TP_SEXO, COD_MUNICIPIO_INSC, NO_MUNICIPIO_INSC, UF_INSC, ST_CONCLUSAO, TP_ANO_CONCLUIU, 
TP_ESCOLA, IN_TP_ENSINO, TP_ESTADO_CIVIL, TP_COR_RACA, IN_UNIDADE_HOSPITALAR, IN_BAIXA_VISAO, IN_CEGUEIRA, IN_SURDEZ, 
IN_DEFICIENCIA_AUDITIVA, IN_SURDO_CEGUEIRA, IN_DEFICIENCIA_FISICA, IN_DEFICIENCIA_MENTAL, IN_DEFICIT_ATENCAO, IN_DISLEXIA, 
IN_GESTANTE, IN_LACTANTE, IN_IDOSO, IN_AUTISMO, IN_SABATISTA, IN_BRAILLE, IN_AMPLIADA_18, IN_LEDOR, IN_ACESSO, IN_TRANSCRICAO, 
IN_LIBRAS, IN_LEITURA_LABIAL, IN_MESA_CADEIRA_RODAS, IN_MESA_CADEIRA_SEPARADA, IN_APOIO_PERNA, IN_GUIA_INTERPRETE, 
IN_CERTIFICADO, NO_ENTIDADE_CERTIFICACAO, SG_UF_ENTIDADE_CERTIFICACAO, PK_COD_ENTIDADE, CO_MUNICIPIO_ESC, NO_MUNICIPIO_ESC, 
SG_UF_ESC, ID_DEPENDENCIA_ADM_ESC, ID_LOCALIZACAO_ESC, SIT_FUNC_ESC, CO_MUNICIPIO_PROVA, NO_MUNICIPIO_PROVA, UF_MUNICIPIO_PROVA, IN_PRESENCA_CN, 
IN_PRESENCA_CH, IN_PRESENCA_LC, IN_PRESENCA_MT, NU_NT_CN, NU_NT_CH, NU_NT_LC, NU_NT_MT, TX_RESPOSTAS_CN, TX_RESPOSTAS_CH, 
TX_RESPOSTAS_LC, TX_RESPOSTAS_MT, CO_PROVA_CN, CO_PROVA_CH, CO_PROVA_LC, CO_PROVA_MT, TP_LINGUA, GABARITO_CN, GABARITO_CH, 
GABARITO_LC, GABARITO_MT, IN_STATUS_REDACAO, NU_NOTA_COMP1, NU_NOTA_COMP2, NU_NOTA_COMP3, NU_NOTA_COMP4, NU_NOTA_COMP5, NU_NOTA_REDACAO
)
FROM '/home/ppca/DADOS_ENEM_2012_utf-8.csv'
WITH header = true 
AND delimiter = ','
AND CHUNKSIZE=1
AND NULL='null'
AND DECIMALSEP='.';


sed -i 's/\"//g' DADOS_ENEM_2012_utf-8.csv 
sed -i 's/,\./,/g' DADOS_ENEM_2012_utf-8.csv 
sed -i 's/,P,/,1,/g' DADOS_ENEM_2012_utf-8.csv 
sed -i 's/,N,/,2,/g' DADOS_ENEM_2012_utf-8.csv 
sed -i 's/,C,/,3,/g' DADOS_ENEM_2012_utf-8.csv 
sed -i 's/,B,/,4,/g' DADOS_ENEM_2012_utf-8.csv 
sed -i 's/,T,/,6,/g' DADOS_ENEM_2012_utf-8.csv 
sed -i 's/,A,/,7,/g' DADOS_ENEM_2012_utf-8.csv 
sed -i 's/,I,/,8,/g' DADOS_ENEM_2012_utf-8.csv 
sed -i 's/,H,/,2,/g' DADOS_ENEM_2012_utf-8.csv 
sed -i 's/,F,/,4,/g' DADOS_ENEM_2012_utf-8.csv 