COPY enem (
NU_INSCRICAO,NU_ANO,NU_IDADE,TP_SEXO,COD_MUNICIPIO_INSC,NO_MUNICIPIO_INSC,UF_INSC,ST_CONCLUSAO,IN_TP_ENSINO,IN_CERTIFICADO,
IN_BRAILLE,IN_AMPLIADA_18,IN_LEDOR,IN_ACESSO,IN_TRANSCRICAO,IN_LIBRAS,IN_UNIDADE_PRISIONAL,IN_BAIXA_VISAO,IN_CEGUEIRA,
IN_DEFICIENCIA_AUDITIVA,IN_DEFICIENCIA_FISICA,IN_DEFICIENCIA_MENTAL,IN_DEFICIT_ATENCAO,IN_DISLEXIA,IN_GESTANTE,IN_LACTANTE,
IN_LEITURA_LABIAL,IN_SABATISTA,IN_SURDEZ,TP_ESTADO_CIVIL,TP_COR_RACA,PK_COD_ENTIDADE,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,SG_UF_ESC,
ID_DEPENDENCIA_ADM_ESC,ID_LOCALIZACAO_ESC,SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,UF_MUNICIPIO_PROVA,IN_PRESENCA_CN,
IN_PRESENCA_CH,IN_PRESENCA_LC,IN_PRESENCA_MT,NU_NT_CN,NU_NT_CH,NU_NT_LC,NU_NT_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,
TX_RESPOSTAS_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,TP_LINGUA,GABARITO_CN,GABARITO_CH,GABARITO_LC,GABARITO_MT,
IN_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,IN_CONCLUINTE_CENSO,
COD_ETAPA_ENSINO_CENSO,COD_ENTIDADE_CENSO,COD_MUNICIPIO_ESC_CENSO,NO_MUNICIPIO_ESC_CENSO,UF_ESC_CENSO,
ID_DEPENDENCIA_ADM_CENSO,ID_LOCALIZACAO_CENSO,SIT_FUNC_CENSO
)
FROM '/home/ppca/2011.csv'
WITH header = false 
AND delimiter = ';'
AND CHUNKSIZE=1
AND NULL='null'
AND DECIMALSEP='.';


sed -i 's/;P;/;1;/g' 2011.csv 
sed -i 's/;N;/;2;/g' 2011.csv 
sed -i 's/;C;/;3;/g' 2011.csv 
sed -i 's/;B;/;4;/g' 2011.csv 
sed -i 's/;T;/;6;/g' 2011.csv 
sed -i 's/;A;/;7;/g' 2011.csv 
sed -i 's/;I;/;8;/g' 2011.csv 
sed -i 's/;H;/;2;/g' 2011.csv 
sed -i 's/;F;/;4;/g' 2011.csv 
sed -i 's/;D;/;5;/g' 2011.csv 




