
DROP INDEX  IX_1;
DROP INDEX  IX_2 ;
DROP INDEX  IX_3;
DROP INDEX  IX_4 ;
DROP INDEX  IX_5 ;
DROP INDEX  IX_6 ;
DROP INDEX  IX_7 ;
DROP INDEX  IX_8;
DROP INDEX  IX_9 ;
DROP INDEX  IX_10;
DROP INDEX  IX_11;
DROP INDEX  IX_12 ;
DROP INDEX  IX_13 ;
DROP INDEX  IX_14;
DROP INDEX  IX_15;
DROP INDEX  IX_16;
DROP INDEX  IX_17; 
DROP INDEX  IX_18;
DROP INDEX  IX_19 ;
DROP INDEX  IX_20;
DROP INDEX  IX_21 ;
DROP INDEX  IX_22;
DROP INDEX  IX_23;
DROP INDEX  IX_24 ;
DROP INDEX  IX_25 ;
DROP INDEX  IX_26 ;
DROP INDEX  IX_27 ;
DROP INDEX  IX_28 ;
DROP INDEX  IX_29 ;
DROP INDEX  IX_30 ;

DROP INDEX  IX_31 ;
DROP INDEX  IX_32;
DROP INDEX  IX_33 ;
DROP INDEX  IX_34;
DROP INDEX  IX_35 ;
DROP INDEX  IX_36;
DROP INDEX  IX_37 ;
DROP INDEX  IX_38 ;
DROP INDEX  IX_39 ;
DROP INDEX  IX_40 ;
DROP INDEX  IX_41 ;
DROP INDEX  IX_42;
DROP INDEX  IX_43 ;
DROP INDEX  IX_44;
DROP INDEX  IX_45 ;
DROP INDEX  IX_46 ;
DROP INDEX  IX_47 ;
DROP INDEX  IX_48;
DROP INDEX  IX_49;
DROP INDEX  IX_50 ;
DROP INDEX  IX_51;
DROP INDEX  IX_52 ;
DROP INDEX  IX_53 ;
DROP INDEX  IX_54;
DROP INDEX  IX_55;
DROP INDEX  IX_56 ;
DROP INDEX  IX_57;
DROP INDEX  IX_58;
DROP INDEX  IX_59 ;
DROP INDEX  IX_60 ;
DROP INDEX  IX_61 ;
DROP INDEX  IX_62 ;
DROP INDEX  IX_63;
DROP INDEX  IX_64;
DROP INDEX  IX_65;
DROP INDEX  IX_66;
DROP INDEX  IX_67 ;
DROP INDEX  IX_68;
DROP INDEX  IX_69 ;
DROP INDEX  IX_70 ;
DROP INDEX  IX_71;
DROP INDEX  IX_72 ;
DROP INDEX  IX_73;
DROP INDEX  IX_74 ;
DROP INDEX  IX_75;
DROP INDEX  IX_76 ;
DROP INDEX  IX_77 ;
DROP INDEX  IX_78;
DROP INDEX  IX_79 ;
DROP INDEX  IX_80 ;


DROP INDEX  IX_81;
DROP INDEX  IX_82 ;
DROP INDEX  IX_83 ;
DROP INDEX  IX_84 ;
DROP INDEX  IX_85 ;
DROP INDEX  IX_86;
DROP INDEX  IX_87 ;
DROP INDEX  IX_88 ;
DROP INDEX  IX_89 ;
DROP INDEX  IX_90;
DROP INDEX  IX_91 ;
DROP INDEX  IX_92 ;
DROP INDEX  IX_93 ;
DROP INDEX  IX_94 ;
DROP INDEX  IX_95 ;
DROP INDEX  IX_96;
DROP INDEX  IX_97 ;
DROP INDEX  IX_98;
DROP INDEX  IX_99 ;
DROP INDEX  IX_100 ;
DROP INDEX  IX_101 ;
DROP INDEX  IX_102;
DROP INDEX  IX_103 ;
DROP INDEX  IX_104 ;
DROP INDEX  IX_105;
DROP INDEX  IX_106 ;
DROP INDEX  IX_107 ;
DROP INDEX  IX_108 ;
DROP INDEX  IX_109 ;
DROP INDEX  IX_110;
DROP INDEX  IX_111 ;
DROP INDEX  IX_112 ;
DROP INDEX  IX_113;
DROP INDEX  IX_114 ;
DROP INDEX  IX_115 ;
DROP INDEX  IX_116;
DROP INDEX  IX_117 ;
DROP INDEX  IX_118;
DROP INDEX  IX_119 ;
DROP INDEX  IX_120;
DROP INDEX  IX_121 ;
DROP INDEX  IX_122 ;
DROP INDEX  IX_123 ;
DROP INDEX  IX_124;
DROP INDEX  IX_125 ;
DROP INDEX  IX_126 ;
DROP INDEX  IX_127;
DROP INDEX  IX_128 ;
DROP INDEX  IX_129;
DROP INDEX  IX_130 ;
DROP INDEX  IX_131 ;
DROP INDEX  IX_132 ;
DROP INDEX  IX_133 ;
DROP INDEX  IX_134 ;
DROP INDEX  IX_135 ;
DROP INDEX  IX_136 ;
DROP INDEX  IX_137;
DROP INDEX  IX_138 ;
DROP INDEX  IX_139;
DROP INDEX  IX_140;
DROP INDEX  IX_141 ;
DROP INDEX  IX_142 ;
DROP INDEX  IX_143 ;
DROP INDEX  IX_144;
DROP INDEX  IX_145;
DROP INDEX  IX_146 ;
DROP INDEX  IX_147 ;
DROP INDEX  IX_148 ;
DROP INDEX  IX_149 ;
DROP INDEX  IX_150 ;
DROP INDEX  IX_151 ;
DROP INDEX  IX_152;
DROP INDEX  IX_153 ;
DROP INDEX  IX_154 ;
DROP INDEX  IX_155;
DROP INDEX  IX_156 ;
DROP INDEX  IX_157 ;

"CREATE INDEX IF NOT EXISTS IX_16 ON microdados.enem ( CO_MUNICIPIO_PROVA );"

micro
"CREATE INDEX IF NOT EXISTS IX_1 ON microdados.enem ( TP_LINGUA );"
"CREATE INDEX IF NOT EXISTS IX_2 ON microdados.enem ( IN_PRESENCA_MT );"
"CREATE INDEX IF NOT EXISTS IX_3 ON microdados.enem ( CO_UF_ESC );"
"CREATE INDEX IF NOT EXISTS IX_4 ON microdados.enem ( IN_OUTRA_DEF );"
"CREATE INDEX IF NOT EXISTS IX_5 ON microdados.enem ( NU_ANO );"
"CREATE INDEX IF NOT EXISTS IX_6 ON microdados.enem ( TX_GABARITO_CN );"
"CREATE INDEX IF NOT EXISTS IX_7 ON microdados.enem ( IN_LACTANTE );"
"CREATE INDEX IF NOT EXISTS IX_8 ON microdados.enem ( IN_DEFICIENCIA_AUDITIVA );"
"CREATE INDEX IF NOT EXISTS IX_9 ON microdados.enem ( TP_SIT_FUNC_ESC );"
"CREATE INDEX IF NOT EXISTS IX_10 ON microdados.enem ( TP_ST_CONCLUSAO );"
"CREATE INDEX IF NOT EXISTS IX_11 ON microdados.enem ( IN_PRESENCA_CN );"
"CREATE INDEX IF NOT EXISTS IX_12 ON microdados.enem ( GABARITO_LC );"
"CREATE INDEX IF NOT EXISTS IX_13 ON microdados.enem ( SG_UF_RESIDENCIA );"
"CREATE INDEX IF NOT EXISTS IX_14 ON microdados.enem ( NU_NOTA_COMP4 );"
"CREATE INDEX IF NOT EXISTS IX_15 ON microdados.enem ( ID_DEPENDENCIA_ADM_ESC );"
"CREATE INDEX IF NOT EXISTS IX_16 ON microdados.enem ( CO_MUNICIPIO_PROVA );"
"CREATE INDEX IF NOT EXISTS IX_17 ON microdados.enem ( NO_MUNICIPIO_NASCIMENTO );"
"CREATE INDEX IF NOT EXISTS IX_18 ON microdados.enem ( IN_MOBILIARIO_ESPECIFICO );"
"CREATE INDEX IF NOT EXISTS IX_19 ON microdados.enem ( IN_SONDA );"
"CREATE INDEX IF NOT EXISTS IX_20 ON microdados.enem ( IN_PROVA_DEITADO );"
"CREATE INDEX IF NOT EXISTS IX_21 ON microdados.enem ( Q021 );"
"CREATE INDEX IF NOT EXISTS IX_22 ON microdados.enem ( NO_MUNICIPIO_ESC );"
"CREATE INDEX IF NOT EXISTS IX_23 ON microdados.enem ( TP_LOCALIZACAO_ESC );"
"CREATE INDEX IF NOT EXISTS IX_24 ON microdados.enem ( NU_NOTA_CH );"
"CREATE INDEX IF NOT EXISTS IX_25 ON microdados.enem ( IN_CADEIRA_ESPECIAL );"
"CREATE INDEX IF NOT EXISTS IX_26 ON microdados.enem ( NU_NOTA_COMP3 );"
"CREATE INDEX IF NOT EXISTS IX_27 ON microdados.enem ( Q013 );"
"CREATE INDEX IF NOT EXISTS IX_28 ON microdados.enem ( IN_CEGUEIRA );"
"CREATE INDEX IF NOT EXISTS IX_29 ON microdados.enem ( Q005 );"
"CREATE INDEX IF NOT EXISTS IX_30 ON microdados.enem ( NO_MUNICIPIO_ESC_CENSO );"
"CREATE INDEX IF NOT EXISTS IX_31 ON microdados.enem ( CO_MUNICIPIO_NASCIMENTO );"
"CREATE INDEX IF NOT EXISTS IX_32 ON microdados.enem ( TX_RESPOSTAS_CH );"
"CREATE INDEX IF NOT EXISTS IX_33 ON microdados.enem ( IN_LEDOR );"
"CREATE INDEX IF NOT EXISTS IX_34 ON microdados.enem ( IN_AMPLIADA_18 );"
"CREATE INDEX IF NOT EXISTS IX_35 ON microdados.enem ( SG_UF_ESC );"
"CREATE INDEX IF NOT EXISTS IX_36 ON microdados.enem ( NU_NOTA_COMP2 );"
"CREATE INDEX IF NOT EXISTS IX_37 ON microdados.enem ( IN_SALA_INDIVIDUAL );"
"CREATE INDEX IF NOT EXISTS IX_38 ON microdados.enem ( NU_NT_CH );"
"CREATE INDEX IF NOT EXISTS IX_39 ON microdados.enem ( IN_PROTETOR_AURICULAR );"
"CREATE INDEX IF NOT EXISTS IX_40 ON microdados.enem ( IN_SOROBAN );"
"CREATE INDEX IF NOT EXISTS IX_41 ON microdados.enem ( NU_NT_CN );"
"CREATE INDEX IF NOT EXISTS IX_42 ON microdados.enem ( Q009 );"
"CREATE INDEX IF NOT EXISTS IX_43 ON microdados.enem ( IN_MATERIAL_ESPECIFICO );"
"CREATE INDEX IF NOT EXISTS IX_44 ON microdados.enem ( GABARITO_CN );"
"CREATE INDEX IF NOT EXISTS IX_45 ON microdados.enem ( IN_CONCLUINTE_CENSO );"
"CREATE INDEX IF NOT EXISTS IX_46 ON microdados.enem ( CO_PROVA_LC );"
"CREATE INDEX IF NOT EXISTS IX_47 ON microdados.enem ( NACIONALIDADE );"
"CREATE INDEX IF NOT EXISTS IX_48 ON microdados.enem ( TP_STATUS_REDACAO );"
"CREATE INDEX IF NOT EXISTS IX_49 ON microdados.enem ( IN_GUIA_INTERPRETE );"
"CREATE INDEX IF NOT EXISTS IX_50 ON microdados.enem ( Q011 );"
"CREATE INDEX IF NOT EXISTS IX_51 ON microdados.enem ( UF_INSC );"
"CREATE INDEX IF NOT EXISTS IX_52 ON microdados.enem ( IN_APOIO_PERNA );"
"CREATE INDEX IF NOT EXISTS IX_53 ON microdados.enem ( Q007 );"
"CREATE INDEX IF NOT EXISTS IX_54 ON microdados.enem ( IN_MARCA_PASSO );"
"CREATE INDEX IF NOT EXISTS IX_55 ON microdados.enem ( TX_RESPOSTAS_CN );"
"CREATE INDEX IF NOT EXISTS IX_56 ON microdados.enem ( Q006 );"
"CREATE INDEX IF NOT EXISTS IX_57 ON microdados.enem ( IN_LEITURA_LABIAL );"
"CREATE INDEX IF NOT EXISTS IX_58 ON microdados.enem ( IN_SALA_ACOMPANHANTE );"
"CREATE INDEX IF NOT EXISTS IX_59 ON microdados.enem ( IN_MESA_CADEIRA_RODAS );"
"CREATE INDEX IF NOT EXISTS IX_60 ON microdados.enem ( IN_MOBILIARIO_OBESO );"
"CREATE INDEX IF NOT EXISTS IX_61 ON microdados.enem ( COD_ETAPA_ENSINO_CENSO );"
"CREATE INDEX IF NOT EXISTS IX_62 ON microdados.enem ( NO_MUNICIPIO_RESIDENCIA );"
"CREATE INDEX IF NOT EXISTS IX_63 ON microdados.enem ( Q018 );"
"CREATE INDEX IF NOT EXISTS IX_64 ON microdados.enem ( IN_AUTISMO );"
"CREATE INDEX IF NOT EXISTS IX_65 ON microdados.enem ( CO_UF_PROVA );"
"CREATE INDEX IF NOT EXISTS IX_66 ON microdados.enem ( IN_SALA_ESPECIAL );"
"CREATE INDEX IF NOT EXISTS IX_67 ON microdados.enem ( NU_NT_MT );"
"CREATE INDEX IF NOT EXISTS IX_68 ON microdados.enem ( ST_CONCLUSAO );"
"CREATE INDEX IF NOT EXISTS IX_69 ON microdados.enem ( NU_NT_LC );"
"CREATE INDEX IF NOT EXISTS IX_70 ON microdados.enem ( IN_STATUS_REDACAO );"
"CREATE INDEX IF NOT EXISTS IX_71 ON microdados.enem ( TP_PRESENCA_LC );"
"CREATE INDEX IF NOT EXISTS IX_72 ON microdados.enem ( IN_COMPUTADOR );"
"CREATE INDEX IF NOT EXISTS IX_73 ON microdados.enem ( TP_ESTADO_CIVIL );"
"CREATE INDEX IF NOT EXISTS IX_74 ON microdados.enem ( COD_MUNICIPIO_ESC_CENSO );"
"CREATE INDEX IF NOT EXISTS IX_75 ON microdados.enem ( IN_NOME_SOCIAL );"
"CREATE INDEX IF NOT EXISTS IX_76 ON microdados.enem ( ID_DEPENDENCIA_ADM_CENSO );"
"CREATE INDEX IF NOT EXISTS IX_77 ON microdados.enem ( Q020 );"
"CREATE INDEX IF NOT EXISTS IX_78 ON microdados.enem ( Q015 );"
"CREATE INDEX IF NOT EXISTS IX_79 ON microdados.enem ( IN_CADEIRA_CANHOTO );"
"CREATE INDEX IF NOT EXISTS IX_80 ON microdados.enem ( CO_ESCOLA );"
"CREATE INDEX IF NOT EXISTS IX_81 ON microdados.enem ( TP_SEXO );"
"CREATE INDEX IF NOT EXISTS IX_82 ON microdados.enem ( TP_ENSINO );"
"CREATE INDEX IF NOT EXISTS IX_83 ON microdados.enem ( IN_MEDICAMENTOS );"
"CREATE INDEX IF NOT EXISTS IX_84 ON microdados.enem ( IN_DEFICIENCIA_MENTAL );"
"CREATE INDEX IF NOT EXISTS IX_85 ON microdados.enem ( SG_UF_NASCIMENTO );"
"CREATE INDEX IF NOT EXISTS IX_86 ON microdados.enem ( SG_UF_PROVA );"
"CREATE INDEX IF NOT EXISTS IX_87 ON microdados.enem ( CO_PROVA_MT );"
"CREATE INDEX IF NOT EXISTS IX_88 ON microdados.enem ( NU_NOTA_CN );"
"CREATE INDEX IF NOT EXISTS IX_89 ON microdados.enem ( IN_PRESENCA_CH );"
"CREATE INDEX IF NOT EXISTS IX_90 ON microdados.enem ( CO_PROVA_CH );"
"CREATE INDEX IF NOT EXISTS IX_91 ON microdados.enem ( TX_GABARITO_CH );"
"CREATE INDEX IF NOT EXISTS IX_92 ON microdados.enem ( SIT_FUNC_ESC );"
"CREATE INDEX IF NOT EXISTS IX_93 ON microdados.enem ( IN_TP_ENSINO );"
"CREATE INDEX IF NOT EXISTS IX_94 ON microdados.enem ( IN_PRESENCA_LC );"
"CREATE INDEX IF NOT EXISTS IX_95 ON microdados.enem ( IN_ESTUDA_CLASSE_HOSPITALAR );"
"CREATE INDEX IF NOT EXISTS IX_96 ON microdados.enem ( CO_UF_ENTIDADE_CERTIFICACAO );"
"CREATE INDEX IF NOT EXISTS IX_97 ON microdados.enem ( TP_PRESENCA_CN );"
"CREATE INDEX IF NOT EXISTS IX_98 ON microdados.enem ( UF_MUNICIPIO_PROVA );"

PROD 
